@startuml

class Galeria {
    -Ventas historial
    +float getOferta(Cuadro)
    +bool vender(Cuadro, Cliente, float precio)
    +float calculaPrecio(Cuadro)
}

class Ventas {
    -vector<Venta> lista_ventas
    +Venta getSimilar(Cuadro)
}

class Cuadro {
    -string autor
    -float precio_inicial
}

class Cliente {
    -string nombre
    -string direccion
}

class Venta {
    -float precio
    -date fecha
    -Cuadro pintura
    -Cliente comprador
    +float generaPrecio()
}

Galeria --* Ventas
Ventas --* Venta
Venta --> Cuadro
Venta --> Cliente

@enduml